#!/bin/bash

#	Author:	@vipink1203
#	Web:	www.webnuxpro.com
#	Script	to perform backup of files and database
#	Last	Edited:	March	4	2017

read -p "Enter the directory you want to backup: " directory
read -p "Enter the directory name where you want to store the backup: " backup_dir

test -d $HOME/$backup_dir || mkdir -m 700 $HOME/$backup_dir

tar -cjvf $HOME/$backup_dir/${directory}_$(date '+%y-%m-%d').tar.bz2 $directory > /dev/null 2>&1

echo "**********************************************************"
echo "                   Backup completed                       "
echo "**********************************************************"
echo 
sleep 2

read -sp "Press any key to continue: " choice

read -p "Enter the database name you want to backup: " database_name
read -p "Enter the username: " database_user
read -sp "Enter the password: " database_pass
echo
mysqldump -u$database_user -p$database_pass $database_name > $HOME/$backup_dir/${database_name}_$(date '+%y-%m-%d').sql

echo "**********************************************************"
echo "                   Database Backup completed              "
echo "**********************************************************"
echo 
echo 
echo "Your backup files are stored under $HOME/$backup_dir/"



