#!/bin/bash

#	Author:	@vipink1203
#	Web:	www.webnuxpro.com
#	Script to check the size of a directory. If its greater than 3 GB, then it would remove the old files keeping the latest 2 days.
#	Last	Edited:	March	6	2017


if [ "$1" == "" ]; then
  echo "Usage: <script.sh> <directory path>"
  exit 1
fi

dir=$1

if [ -d $1 ]; then
	size=$(du -s --block-size=G $1 | cut -c1-1 )
	if [ $size -gt 3 ]; then
		search=`find $1 -type f -mtime +2 | xargs rm --`
		echo $search > removedfiles.log
	else
    		echo "Size is less than 3 GB."
	fi
else
  echo "The passed parameter is not a directory"
  echo "Usage: <script.sh> <directory path>"
  exit

fi
