#!/bin/bash

#	Author:	@vipink1203
#	Web:	www.webnuxpro.com
#	Script	to ping the server and success message will be displayed. You can pipe the echo output to any mail sending tool like mutt if needed.
#	Last	Edited:	March	4	2017

if [ "$1" == "" ]; then
	echo "Usage: script.sh <Server IP>"
else 
ping -c3 $1 > /dev/null 2>&1 && echo "Server is up and running" || echo "$1 is down..."

fi
